---
- name: Create file on hosts
  hosts: all
  tasks:
    - name: Create files
      file:
        path: /tmp/file{1..5}
        state: touch
        access_time: 20180501
      when: ansible_distribution == "CentOS"
